from __future__ import annotations

from datetime import datetime

from sqlalchemy import Boolean, Float, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, UTCDateTime, utcnow


class Segment(Base):
    """One continuous stretch of one window being in the foreground.

    `uid` is generated by the collector so that re-sending an open segment
    updates it in place instead of duplicating it. Everything is stored in
    UTC; the UI converts for display.
    """

    __tablename__ = "segments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    uid: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    host: Mapped[str] = mapped_column(String(120), default="", index=True)

    exe: Mapped[str] = mapped_column(String(255), index=True)
    title: Mapped[str] = mapped_column(Text, default="")

    category: Mapped[str] = mapped_column(String(64), index=True, default="uncategorized")
    bucket: Mapped[str] = mapped_column(String(32), index=True, default="neutral")
    rule_id: Mapped[str] = mapped_column(String(64), default="")

    started_at: Mapped[datetime] = mapped_column(UTCDateTime, index=True)
    ended_at: Mapped[datetime] = mapped_column(UTCDateTime, index=True)
    duration_s: Mapped[float] = mapped_column(Float, default=0.0)

    is_closed: Mapped[bool] = mapped_column(Boolean, default=True, index=True)

    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        UTCDateTime, default=utcnow, onupdate=utcnow
    )

    __table_args__ = (
        Index("ix_segments_started_category", "started_at", "category"),
        Index("ix_segments_started_bucket", "started_at", "bucket"),
    )
